#!/bin/sh

set -e

for test in test/*.unl
do
    if [ -e ${test%.unl}.in ]
    then
	$1 $test <${test%.unl}.in |diff -u ${test%.unl}.out -
    else
	$1 $test |diff -u ${test%.unl}.out -
    fi
done

# Materializing a continuation larger than the young generation must keep
# collecting until promoted frames leave room for the next cell.
awk 'BEGIN {
    n = 300000
    for (i = 0; i < n + 1; i++) printf "`"
    printf "ce"
    for (i = 0; i < n; i++) printf "i"
}' | "$1" >/dev/null

echo 'All tests passed'
